import pandas as pd

# Define the table data
data = {
    "Variable Type": [
        "Projected Demographics 2030", "Projected Demographics 2030", "Demographic Variables", 
        "Demographic Variables", "Demographic Variables", "Demographic Variables", 
        "Floating Population", "Floating Population", "Households", "Households", 
        "Sanitation Coverage Variables", "Sanitation Coverage Variables", 
        "Sanitation Coverage Variables", "Human Excreta Management", 
        "Human Excreta Management", "Human Excreta Management", "Human Excreta Management", 
        "Human Excreta Management", "Tourism data", "Open Defecation", "Water Supply", 
        "School Sanitation", "School Sanitation", "School Sanitation", "Health Variables", 
        "Health Variables", "Health Variables", "Health Variables", "Health Variables", 
        "Economic Variables", "Economic Variables", "Urban-Specific Variables", 
        "Urban-Specific Variables", "Cost Metric", "Piped Water Supply Costs", 
        "Capital Costs", "Capital Costs", "Capital Costs", "Capital Costs", 
        "Operational Costs", "Operational Costs", "Operational Costs", "Operational Costs", 
        "Operational Costs", "Training and Outreach Costs", "Training and Outreach Costs", 
        "Benefit Metric", "Health Benefits", "Health Benefits", "Health Benefits", 
        "Health Benefits", "Health Benefits", "Economic Benefits", "Economic Benefits", 
        "Economic Benefits", "Economic Benefits", "Economic Benefits", 
        "Value of loss-of-life avoided", "Value of loss-of-life avoided", 
        "Value of loss-of-life avoided", "Value of loss-of-life avoided"
    ],
    "Variable Name": [
        "Population", "Number of Households", "Population", "Population", "Population", 
        "Population", "Floating Population", "Floating Population", "Households", 
        "Households", "Access to Toilets", "Access to Toilets", "Access to Toilets", 
        "Human Excreta Management", "Human Excreta Management", "Human Excreta Management", 
        "Human Excreta Management", "Human Excreta Management", "Tourism data", 
        "Open Defecation", "Distribution of drinking water facilities", 
        "No. Of school-going children", "No. Of school-going children", 
        "School Sanitation coverage", "Incidence of Waterborne/Vector Diseases", 
        "Incidence of Waterborne/Vector Diseases", "Birth & Death rate", 
        "Birth & Death rate", "Type of diseases", "Population Income", "GDP", 
        "Sewage System Coverage", "Onsite Sanitation System", "Cost Metric", 
        "Functional Household Tap Connection (FHTC) cost", "Construction Costs", 
        "Construction Costs", "Construction Costs", "Construction Costs", 
        "Maintenance Costs", "Maintenance Costs", "Maintenance Costs", "Maintenance Costs", 
        "Maintenance Costs", "Capacity Building of ULBs", "Public Awareness Campaigns (IEC/BCC)", 
        "Benefit Metric", "Unit cost per treatment (Diarrhea)", 
        "Reduced mortality from diarrheal diseases", 
        "Reduced morbidity from diarrheal diseases", "Visits or days per case", 
        "Hospital commuting costs", "Days off work/school", 
        "Opportunity cost of time for working adults", 
        "Opportunity cost of time for school going children", 
        "Economy due to tourism", "Revenue generation", 
        "Discounted productive years lost (0 – 4 years)", 
        "Discounted productive years lost (5 – 14 years)", 
        "Discounted productive years lost (15+ years)", 
        "Opportunity cost per year of life lost"
    ],
    "Description": [
        "Projected Population – 2030", "Projected no. of households - 2030", 
        "Total Male", "Total Female", "Total Urban Population", "Total Slum Population", 
        "Urban & Slums", "Percentage of Tourist Footfall", 
        "Total Number of Households in Urban", "Total Number of Households in Slums", 
        "Total Number of Households with toilet", "Total Number of Public Toilet", 
        "Total Number of Community Toilet", 
        "Percentage of population connected to sewer system", 
        "Treatment Capacity of STP", "No of STP", "No. of FSTP", "Capacity of FSTP", 
        "Water and sanitation facilities during tourist feast/yaatra/waari", 
        "Percentage of Households Having Access to Any Type of Toilet Facility (e.g., IHHT, CT/PT)", 
        "Percentage of households having tap water supply", 
        "Number of school-going children - Boys", 
        "Number of school-going children - Girls", 
        "School statistics along sanitation arrangements", 
        "Number of cases of Water Borne diseases", 
        "Number of cases of Vector Borne diseases", "Total no. of births", 
        "Total no. of deaths", "No. of diarrheal cases per year", 
        "Average income of households (INR Lakh/Year)", 
        "Revenue Generation from (Water Tax, sewerage tax, CT/PT usage)", 
        "Number of households connected to the sewage system.", 
        "Number of households having septic tanks/soak pit", "Cost Metric", 
        "FHTC cost (Per household) INR", "CT/PT (Per Water Closet) INR Lakhs", 
        "Sewerage Connections (INR lakh per KM)", "STP (Per MLD of wastewater) in INR Crore", 
        "FSTP (Per KLD of Sludge) in INR Lakh", "CT/PT (Per Water Closet cost) INR", 
        "Sewerage Connections (INR thousand per KM)", 
        "STP (Per annum/MLD of wastewater) in INR Lakhs", 
        "FSTP (Per annum/ KLD of wastewater) in INR Lakh", 
        "FSTP Desludging cost", "Costs for educating officials about sanitation", 
        "Expenses for promoting sanitation and hygiene (INR per person annually)", 
        "Benefit Metric", "Savings in healthcare expenses due to improved sanitation.", 
        "Decrease in mortality due to diseases caused by poor sanitation", 
        "Decrease in the incidence of diseases caused by improved sanitation", 
        "Increased productivity due to improved sanitation", 
        "Savings in transport expenses due to improved sanitation.", 
        "Gains in productivity due to fewer sick days.", 
        "Time and money saved as a result of improved sanitation", 
        "Opportunity cost of time for school going children", 
        "Increase in GDP due to tourism as a result of improved sanitation", 
        "Reuse of treated wastewater (INR /m3)", 
        "Years lost as a result of lack of proper sanitation for different age groups", 
        "Years lost as a result of lack of proper sanitation for different age groups", 
        "Years lost as a result of lack of proper sanitation for different age groups", 
        "Opportunity cost per year of life lost"
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Save the DataFrame as a CSV file
df.to_csv("sanitation_variables.csv", index=False)